server:
  port: 2010

spring:
  application:
    name: service-hello-zipkin
  zipkin:
    base-url: http://localhost:40000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/

