server:
  port: 30000
spring:
  application:
    name: zuul-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: ribbon-service
    api-b:
      path: /api-b/**
      serviceId: ribbon-service